apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: my-app
spec:
  source:
    repoURL: https://github.com/SaulMarcial/node-web-app.git
    path: deployment
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  syncPolicy:
    automated: {}
  preSync:
    hooks:
    - name: get-git-release
      container:
        name: get-release
        image: alpine:latest
        command: ["sh", "-c"]
        args: ["./get_release.sh"]