apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: my-app
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/SaulMarcial/node-web-app.git
    targetRevision: HEAD
    path: argo
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
    automated: {}
  preSync:
    hooks:
    - name: get-git-release
      container:
        name: get-release
        image: alpine:latest
        command: ["sh", "-c"]
        args: ["./get_release.sh"]