apiVersion: batch/v1
kind: Job
metadata:
  name: pre-sync-job
  namespace: argocd
  annotations:
    argocd.argoproj.io/hook: PreSync  
spec:
  template:
    spec:
      containers:
      - name: slack-notification
        image: curlimages/curl
        command:
          - "sh"
          - "-c"
          - "release=$(curl -L -H 'Accept: application/vnd.github+json' -H 'Authorization: Bearer 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' -H 'X-GitHub-Api-Version: 2022-11-28' https://api.github.com/repos/SaulMarcial/node-web-app/releases/latest | grep tag_name | awk -F'\"' '{print $4}')"
          - "curl"
          - "-X"
          - "POST"
          - "--data-urlencode"
          - "payload={\"channel\": \"#somechannel\", \"username\": \"hello\", \"text\": \"App Sync succeeded\", \"icon_emoji\": \":ghost:\"}"
          - "https://hooks.slack.com/services/..."
      restartPolicy: Never
  backoffLimit: 2
