apiVersion: batch/v1
kind: Job
metadata:
  generateName: pre-sync-job-
  namespace: argocd
  annotations:
    argocd.argoproj.io/hook: PreSync  
spec:
  template:
    spec:
      containers:
      - name: slack-notification
        image: curlimages/curl
        command:
          - "sh"
          - "-c"
          - |
            release=$(curl -L -H 'Accept: application/vnd.github+json' -H 'Authorization: Bearer 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' -H 'X-GitHub-Api-Version: 2022-11-28' https://api.github.com/repos/SaulMarcial/node-web-app/releases/latest | grep tag_name | awk -F'\"' '{print $4}')
            echo "Release: $release"
      restartPolicy: Never
  backoffLimit: 2
